#!/usr/bin/env bash
#
# Build xemu from a mirror of the working tree placed on a native Linux
# filesystem.
#
# Two problems make building directly from a Windows-hosted checkout painful
# under WSL: every file access crosses the 9p mount, which makes a full build
# many times slower, and a checkout made by Windows git carries CRLF line
# endings, which stops shell scripts running at all because the kernel looks
# for an interpreter named "bash\r".
#
# The mirror is a derived artifact and never a place to work. It is
# reconstructed with "rsync --delete" on every run, so anything edited there is
# destroyed on the next build rather than quietly diverging from the tree you
# actually commit from. Edits belong in the source tree only.
#
# The build directory inside the mirror is preserved between runs so ninja
# stays incremental.

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source_dir="$(cd -- "${script_dir}/.." && pwd)"

# Override with XEMU_WSL_BUILD_ROOT to place the mirror elsewhere.
build_root="${XEMU_WSL_BUILD_ROOT:-${HOME}/.cache/xemu-wsl-build}"

sync_only=0
force=0
clean=0
build_args=()

usage() {
    cat <<EOF
Usage: ${0##*/} [options] [-- build.sh arguments]

  --build-root DIR  Where to place the mirror. Default: \$HOME/.cache/xemu-wsl-build
                    (or \$XEMU_WSL_BUILD_ROOT).
  --sync-only       Refresh the mirror and stop, without building.
  --clean           Delete the mirror's build directory first, forcing a full
                    reconfigure and rebuild.
  --force           Overwrite local modifications in the mirror without asking.
  -h, --help        Show this message.

Anything after -- is passed to build.sh, for example:

  ${0##*/} -- -j8 --debug
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --build-root) shift; build_root="${1:?--build-root needs a path}" ;;
        --sync-only)  sync_only=1 ;;
        --clean)      clean=1 ;;
        --force)      force=1 ;;
        -h|--help)    usage; exit 0 ;;
        --)           shift; build_args=("$@"); break ;;
        *)            echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

command -v rsync >/dev/null 2>&1 || { echo "rsync is required." >&2; exit 1; }

# Guard against mirroring a tree onto itself, which --delete would empty.
if [ "$(cd -- "$source_dir" && pwd -P)" = "$(cd -- "$build_root" 2>/dev/null && pwd -P || echo '')" ]; then
    echo "Build root and source directory are the same. Refusing to run." >&2
    exit 1
fi

# Everything the mirror derives for itself has to survive --delete, or each
# build starts by throwing away work it will only have to redo.
#
# The build directory is the obvious one. Less obviously, meson downloads
# subprojects into the source tree it is building from, which here is the
# mirror rather than the real checkout: deleting those turns every build into a
# fresh download of several hundred megabytes, and makes builds fail outright
# when the network is unavailable.
rsync_opts=(
    --archive
    --delete
    --delete-excluded
    --exclude=/.git/
    --exclude=/.notes/
    --filter=protect_/build/
    --exclude=/build/
    --filter=protect_/subprojects/***
    --filter=protect_/MIRROR_DO_NOT_EDIT
    --exclude=/MIRROR_DO_NOT_EDIT
)

mkdir -p "$build_root"

echo "Source: ${source_dir}"
echo "Mirror: ${build_root}"
echo

# Report anything the sync is about to overwrite or remove, so an accidental
# edit in the mirror is visible rather than silently lost.
if [ -e "${build_root}/meson.build" ]; then
    divergence="$(rsync "${rsync_opts[@]}" --dry-run --itemize-changes \
                        "${source_dir}/" "${build_root}/" | head -40)"
    if [ -n "$divergence" ]; then
        count="$(printf '%s\n' "$divergence" | wc -l)"
        echo "${count} path(s) in the mirror differ from the source and will be replaced:"
        printf '%s\n' "$divergence" | sed 's/^/  /'
        echo
        if [ "$force" -eq 0 ] && [ -t 0 ]; then
            read -r -p "Continue and overwrite the mirror? [y/N] " reply
            case "$reply" in
                [yY]*) ;;
                *) echo "Aborted."; exit 1 ;;
            esac
        fi
    fi
fi

echo "Mirroring..."
rsync "${rsync_opts[@]}" "${source_dir}/" "${build_root}/"

# Record what the mirror was built from, so a stale or hand-edited mirror can
# be identified later.
{
    echo "# Generated by ${0##*/}. This tree is a mirror; do not edit it."
    echo "synced_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    if git -C "$source_dir" rev-parse --git-dir >/dev/null 2>&1; then
        echo "source_commit=$(git -C "$source_dir" rev-parse HEAD 2>/dev/null || echo unknown)"
        echo "source_branch=$(git -C "$source_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
    fi
} > "${build_root}/MIRROR_DO_NOT_EDIT"

# A CRLF checkout produces shebangs the kernel cannot resolve, and the failure
# ("bash\r: No such file or directory") does not name the real cause.
if head -c 128 "${build_root}/build.sh" | grep -q $'\r'; then
    cat >&2 <<EOF

build.sh in the mirror has CRLF line endings, so it will not run.

The repository stores LF, so this comes from the working tree rather than from
git history. Normalise the source tree with:

    git -C "${source_dir}" config core.autocrlf false
    git -C "${source_dir}" config core.eol lf
    git -C "${source_dir}" checkout-index -a -f

Staged changes are preserved; only line endings change.
EOF
    exit 1
fi

if [ "$clean" -eq 1 ]; then
    echo "Removing previous build output..."
    rm -rf "${build_root}/build"
fi

if [ "$sync_only" -eq 1 ]; then
    echo "Mirror is up to date."
    exit 0
fi

if [ ${#build_args[@]} -eq 0 ]; then
    build_args=(-j"$(nproc)")
fi

echo
echo "Building: ./build.sh ${build_args[*]}"
cd "$build_root"
exec ./build.sh "${build_args[@]}"
